version: '3.7'

services:
  environment:
    container_name: environment
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3006:3006
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: node app.js
